### ISSUE TITLE
Hard reset

### ISSUE THREAD

**Issue by Sacro** [danieltwagner/qsw-2104-2s#3]
Is there an internal or external way to hard reset? I had it working on 1.1.1.100, but now it seems to not be responding to pings and only 1 port is lit up orange/red.

It's a QSW-1105-5T if that makes any difference.

**Comment by danieltwagner** [comment]
If you haven't saved the settings then you can reset it by cutting power and it'll come back with the last saved settings. If you did save them and find yourself unable to access the web interface anymore then you can still reset over a serial connection but that will require opening the case.

**Comment by Sacro** [comment]
Thanks, I've got the serial connection up and running but can't seem to get any commands to work.

I think I need to interrupt the bootloader, but I can't figure out that either!

**Comment by danieltwagner** [comment]
Sorry I missed this somehow. Any key should work to interrupt the bootloader... One thing to check is that your serial interface's TX pin is connected to the switch's RX pin (instead of, say, VCC). Doe your connection match the one I mentioned here? https://github.com/danieltwagner/qsw-2104-2s#serial-console

Afterwards you can use `config_get` and `config_set` to amend your config as needed.

**Comment by Sacro** [comment]
I'm trying keys, what line ending should I try? What serial console are you using?

I'm not sure the connection does match, I'm fairly confident that TX is pin 1, and 0/2 must be the GND as one of those is needed to get viewable output. 

That must mean that 4 is VCC.

**Comment by danieltwagner** [comment]
You must have (device) TX and GND correct, otherwise you wouldn't be seeing any console output during boot :)
You could try putting your serial TX on the other uncertain pin. I found that the device tends to pull its RX high so it might be easy to confuse it with VCC. For line endings, I think I've been using CR only but maybe try all of CR, LF, and CR+LF.

I use pyserial because it can be automated easily but it comes with a CLI. I doubt that's what's holding you back, though.

Also have a look at this thread in case one of the 1105-5 users left more useful information there: https://forum.openwrt.org/t/hacking-into-qnap-qsw-1105-5t-2-5g-broadcom-based-switch/109381/1

**Comment by Sacro** [comment]
I've played around a bit with the pins and successfully managed to stop the USB ports on my laptop working.

Tried writing an expect script to send the keypresses, but still not interrupting the boot sequence. Probably RMA time.

**Comment by danieltwagner** [comment]
Yikes, sorry about that. If you're going to keep doing this it might be a good idea to get a galvanically isolated UART adapter; I hope your USB port has recovered... Feel free to re-open if you're running into issues again!
